name: Metrics
on:
  # Schedule weekly updates
  schedule: [{cron: "0 0 * * 1"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.PRIVATE_TOKEN }}
          base:
          repositories_skipped: ${{ secrets.REPOS_TO_SKIP }}
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_colors: rainbow
          plugin_languages_limit: 20
          plugin_languages_threshold: 0%
          plugin_languages_details: percentage
          plugin_languages_sections: recently-used
          
          repositories: '*'
          config_output: svg
